### ISSUE TITLE
RTL logo seems just white space?

### ISSUE THREAD

**Issue by Gilbog** [VajraOfIndra/awesome-bitcoin-logos#1]
Hello, 
thanks for supplying these great logos!
But the Ride The Ligthning logo on your previous page appears to be just white space. Something is wrong with it, I think. Does someone know how to get a nice RTL logo, or can someone fix the one available here?
Thanks a lot!

**Comment by ghost** [comment]
> Hello, thanks for supplying these great logos! But the Ride The Ligthning logo on your previous page appears to be just white space. Something is wrong with it, I think. Does someone know how to get a nice RTL logo, or can someone fix the one available here? Thanks a lot!

The RTL logo right now is white with a transparent background, so it's visible if you use a dark mode but not if you use a white background. I'll try to get a better one!

**Comment by ghost** [comment]
So in their repository they have 2 logos, one which is white and one black, both with transparent backgrounds.. so both are not ideal at all as they could appear as a white or black square depending on the background of the user! :smile: 

I've seen they've got a purple one as well, I'll try to source an official high-res version of it but no luck so far.

**Comment by Gilbog** [comment]
Thanks for the replies, I now understand why I couldn't see the logo initially. I "fixed" my problem by switching the app to "dark theme" for now ... If you do get the purple one, I'll switch to that :)

**Comment by ghost** [comment]
> Thanks for the replies, I now understand why I couldn't see the logo initially. I "fixed" my problem by switching the app to "dark theme" for now ... If you do get the purple one, I'll switch to that :)

Check out the new logo. It's from the official SVG logo but modified with the purple colour found in ridethelightning.info. It should now display properly on any kind of background.

**Comment by ghost** [comment]
Closing as issue has been fixed on May 9th. Feel free to reopen if required!
